# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tYpIwNdcyldmzy3Sf31E89qtaiPlLE1S
"""

# Step 1: Install dependencies
!pip install transformers
!pip install streamlit
!pip install pyngrok
!pip install torch

# Step 2: Write the Streamlit app code to a file
app_code = """
import streamlit as st
from transformers import pipeline

# Load the QA pipeline with BERT-Large model
qa_pipeline = pipeline("question-answering", model="bert-large-uncased-whole-word-masking-finetuned-squad")

# Initialize context in Streamlit session state
if 'context' not in st.session_state:
    st.session_state.context = ""

st.title("QA Chatbot with BERT-Large")

# Context input
context_input = st.text_area("Set the context:", placeholder="Enter context or leave blank to keep previous context.")
if st.button("Update Context"):
    st.session_state.context = context_input
    st.write("Context updated.")

# Display the current context
st.write("Current Context:")
st.write(st.session_state.context)

# Question input
question_input = st.text_input("Ask a question:")
if st.button("Submit"):
    if not st.session_state.context:
        st.write("Please provide a context first.")
    else:
        result = qa_pipeline(question=question_input, context=st.session_state.context)
        st.write(f"Answer: {result['answer']}")
        st.session_state.history.append({"question": question_input, "answer": result['answer']})

# Display conversation history
if 'history' not in st.session_state:
    st.session_state.history = []

if st.session_state.history:
    st.write("Conversation History:")
    for entry in st.session_state.history:
        st.write(f"Q: {entry['question']}")
        st.write(f"A: {entry['answer']}")
"""

# Write the code to app.py
with open("app.py", "w") as file:
    file.write(app_code)

# Step 3: Configure ngrok with your authtoken
from pyngrok import ngrok

# Use your actual authtoken here
!ngrok config add-authtoken 2kom8ZOBBUAXMc0S8CzKUM8d3FR_4Bwdpymun9tUBjkFyN6LK

# Step 4: Run the Streamlit app
!streamlit run app.py &> /dev/null&

# Step 5: Setup and use ngrok
ngrok.kill()

# Explicitly specifying the port
public_url = ngrok.connect(addr="8501")
print(f"Public URL: {public_url}")